/* Auto-generated by build-products.js — NE PAS MODIFIER MANUELLEMENT */
/* Dernière mise à jour: 21/05/2026 15:50:19 */
const products = [
  {
    "id": 1,
    "name": "Coussin de Voyage Gonflable",
    "desc": "Dormez confortablement en avion, en train ou en voiture. Ce coussin gonflable enveloppe votre tête et vos bras pour un soutien complet — plus de réveils douloureux en route.",
    "price": 99,
    "oldPrice": 199,
    "badge": "🔥 Best Seller",
    "folder": "product1",
    "images": [
      "assets/product1/WhatsApp Image 2026-05-20 at 18.24.22 (1).jpeg",
      "assets/product1/WhatsApp Image 2026-05-20 at 18.24.22 (2).jpeg",
      "assets/product1/WhatsApp Image 2026-05-20 at 18.24.22.jpeg",
      "assets/product1/WhatsApp Image 2026-05-20 at 18.24.23 (1).jpeg",
      "assets/product1/WhatsApp Image 2026-05-20 at 18.24.23.jpeg"
    ],
    "video": "assets/product1/WhatsApp Video 2026-05-20 at 18.24.22.mp4"
  },
  {
    "id": 2,
    "name": "Boîte de Rangement Pliable",
    "desc": "Organisez votre espace avec style grâce à cette boîte de rangement élégante, résistante et parfaite pour toutes les pièces.",
    "price": 89,
    "oldPrice": 159,
    "badge": "⚡ Tendance",
    "folder": "product2",
    "images": [
      "assets/product2/WhatsApp Image 2026-05-20 at 18.31.04 (1).jpeg",
      "assets/product2/WhatsApp Image 2026-05-20 at 18.31.04 (2).jpeg",
      "assets/product2/WhatsApp Image 2026-05-20 at 18.31.04 (3).jpeg",
      "assets/product2/WhatsApp Image 2026-05-20 at 18.31.04 (4).jpeg",
      "assets/product2/WhatsApp Image 2026-05-20 at 18.31.04 (5).jpeg",
      "assets/product2/WhatsApp Image 2026-05-20 at 18.31.04.jpeg",
      "assets/product2/WhatsApp Image 2026-05-20 at 18.31.05.jpeg"
    ],
    "video": "assets/product2/WhatsApp Video 2026-05-20 at 18.31.07.mp4"
  },
  {
    "id": 3,
    "name": "Rasoir Anti-Bouloches SONAR SN-229",
    "desc": "Élimine rapidement les bouloches sur vêtements, couvertures et tissus. Recharge USB pratique et design compact ultra moderne.",
    "price": 89,
    "oldPrice": 450,
    "badge": "🆕 Nouveau",
    "folder": "product3",
    "images": [
      "assets/product3/WhatsApp Image 2026-05-20 at 18.39.41 (1).jpeg",
      "assets/product3/WhatsApp Image 2026-05-20 at 18.39.41 (2).jpeg",
      "assets/product3/WhatsApp Image 2026-05-20 at 18.39.41.jpeg",
      "assets/product3/WhatsApp Image 2026-05-20 at 18.39.42 (1).jpeg",
      "assets/product3/WhatsApp Image 2026-05-20 at 18.39.42.jpeg"
    ],
    "video": null
  },
  {
    "id": 4,
    "name": "Ventilateur Portable à Main",
    "desc": "Restez au frais où que vous soyez avec ce ventilateur portable compact et puissant. Parfait pour les voyages, le bureau ou la maison. Design ergonomique et batterie longue durée.",
    "price": 119,
    "oldPrice": 199,
    "badge": "🆕 Nouveau",
    "folder": "product4",
    "images": [
      "assets/product4/azazaz.jpeg",
      "assets/product4/dddza.jpeg",
      "assets/product4/ssss.jpeg",
      "assets/product4/WhatsApp Image 2026-05-21 at 15.35.25.jpeg",
      "assets/product4/zzz.jpeg"
    ],
    "video": "assets/product4/WhatsApp Video 2026-05-21 at 15.35.26.mp4"
  }
];
