/* ===== LUXESTORE — script.js ===== */
/* Products data is loaded from products-data.js (auto-generated by build-products.js) */


// ===== TESTIMONIALS DATA =====
const testimonials = [
  { name: "Yassine M.", location: "Casablanca", text: "Produit reçu en 24h! Qualité incroyable, je recommande à 100%. Service client au top via WhatsApp.", initials: "YM" },
  { name: "Fatima Z.", location: "Rabat", text: "Les écouteurs sont exactement comme dans la vidéo TikTok. Son parfait et le design est magnifique.", initials: "FZ" },
  { name: "Amine K.", location: "Marrakech", text: "Troisième commande chez LUXESTORE. Toujours satisfait. Les prix sont imbattables pour cette qualité.", initials: "AK" },
  { name: "Sara B.", location: "Tanger", text: "La montre connectée est sublime! Mon amie en a commandé une aussi après avoir vu la mienne.", initials: "SB" },
  { name: "Omar H.", location: "Fès", text: "Livraison rapide et produit bien emballé. Le support WhatsApp répond super vite. Top!", initials: "OH" },
  { name: "Nadia L.", location: "Agadir", text: "La lampe sunset est exactement ce que je voulais pour mes photos Instagram. Magnifique!", initials: "NL" }
];

// ===== WHATSAPP NUMBER =====
const WHATSAPP_NUMBER = "212621924487";

// ===== SVG ICONS =====
const whatsappSVG = `<svg viewBox="0 0 32 32" fill="#fff" xmlns="http://www.w3.org/2000/svg"><path d="M16.004 0h-.008C7.174 0 0 7.176 0 16.004c0 3.5 1.132 6.738 3.052 9.374L1.054 31.29l6.154-1.97C9.822 30.982 12.808 32 16.004 32 24.826 32 32 24.826 32 16.004 32 7.176 24.826 0 16.004 0zm9.306 22.612c-.39 1.1-1.932 2.014-3.172 2.28-.848.18-1.956.324-5.684-1.222-4.776-1.978-7.846-6.828-8.084-7.146-.228-.318-1.928-2.568-1.928-4.896s1.222-3.472 1.656-3.948c.434-.476.948-.596 1.264-.596.316 0 .632.002.908.016.292.016.684-.11 1.07.816.39.948 1.328 3.242 1.446 3.478.118.236.196.512.04.83-.158.316-.236.514-.472.79-.236.278-.498.62-.71.832-.236.236-.482.494-.206.968.274.476 1.222 2.016 2.624 3.264 1.806 1.606 3.328 2.102 3.804 2.338.474.236.752.196 1.028-.118.276-.316 1.184-1.382 1.5-1.858.316-.476.632-.394 1.066-.236.434.158 2.762 1.302 3.234 1.54.474.236.79.354.908.552.118.196.118 1.146-.272 2.252z"/></svg>`;

// ===== GENERATE PLACEHOLDER IMAGES (SVG-based) =====
function generateProductImage(product, index) {
  const colors = product.colors || ["#1a1a2e", "#00d4aa", "#f5f5f7"];
  const hue = (product.id * 60 + index * 30) % 360;
  return `data:image/svg+xml,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400">
      <defs>
        <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:hsl(${hue},60%,12%)"/>
          <stop offset="100%" style="stop-color:hsl(${hue + 40},70%,18%)"/>
        </linearGradient>
        <radialGradient id="glow" cx="50%" cy="40%">
          <stop offset="0%" style="stop-color:hsl(${hue + 20},80%,50%);stop-opacity:0.3"/>
          <stop offset="100%" style="stop-color:transparent"/>
        </radialGradient>
      </defs>
      <rect width="600" height="400" fill="url(#g)"/>
      <circle cx="300" cy="180" r="120" fill="url(#glow)"/>
      <rect x="220" y="130" width="160" height="100" rx="16" fill="hsl(${hue + 20},60%,30%)" opacity="0.6"/>
      <circle cx="300" cy="180" r="30" fill="hsl(${hue},80%,60%)" opacity="0.8"/>
      <text x="300" y="340" text-anchor="middle" font-family="Inter,sans-serif" font-size="14" fill="rgba(255,255,255,0.3)">${product.name}</text>
    </svg>
  `)}`;
}

// ===== RENDER PRODUCTS =====
function renderProducts() {
  const grid = document.getElementById("productsGrid");
  grid.innerHTML = products.map((p, idx) => {
    // Build media slides: images + video
    let slides = [];
    if (p.images && p.images.length > 0) {
      p.images.forEach((src, i) => {
        slides.push(`<img src="${src}" alt="${p.name} - photo ${i+1}" class="product-slide ${i === 0 ? 'active' : ''}" data-idx="${slides.length}">`);
      });
    } else {
      const img1 = p.img1 || generateProductImage(p, 0);
      const img2 = p.img2 || generateProductImage(p, 1);
      slides.push(`<img src="${img1}" alt="${p.name}" class="product-slide active" data-idx="0">`);
      slides.push(`<img src="${img2}" alt="${p.name} vue 2" class="product-slide" data-idx="1">`);
    }
    if (p.video) {
      slides.push(`<video src="${p.video}" class="product-slide" data-idx="${slides.length}" muted loop playsinline></video>`);
    }
    const dotsHTML = slides.map((_, i) => `<span class="media-dot ${i === 0 ? 'active' : ''}" data-slide="${i}"></span>`).join('');
    const waMsg = encodeURIComponent(`Bonjour! Je suis intéressé(e) par: ${p.name} (${p.price} MAD). Est-il disponible?`);
    return `
      <div class="product-card reveal nano-float" style="animation-delay: ${idx * 0.15}s">
        <a href="product.html?id=${p.id}" class="product-media" style="display:block;">
          <span class="product-badge">${p.badge}</span>
          ${slides.join('\n          ')}
          <div class="media-nav" onclick="event.preventDefault(); event.stopPropagation();">
            ${dotsHTML}
          </div>
        </a>
        <div class="product-info">
          <a href="product.html?id=${p.id}"><h3 class="product-name">${p.name}</h3></a>
          <p class="product-desc">${p.desc}</p>
          <div class="product-price-row">
            <span class="product-price">${p.price} MAD</span>
            <span class="product-old-price">${p.oldPrice} MAD</span>
          </div>
          <a href="https://wa.me/${WHATSAPP_NUMBER}?text=${waMsg}" target="_blank" class="btn-whatsapp magnetic-btn">
            ${whatsappSVG}
            Commander via WhatsApp
          </a>
        </div>
      </div>
    `;
  }).join("");

  // Product media slider with swipe support
  document.querySelectorAll(".product-card").forEach(card => {
    const slides = card.querySelectorAll(".product-slide");
    const dots = card.querySelectorAll(".media-dot");
    let current = 0;

    function goToSlide(idx) {
      slides.forEach(s => { s.style.display = "none"; s.classList.remove("active"); if (s.tagName === "VIDEO") s.pause(); });
      dots.forEach(d => d.classList.remove("active"));
      slides[idx].style.display = "block";
      slides[idx].classList.add("active");
      dots[idx].classList.add("active");
      if (slides[idx].tagName === "VIDEO") { slides[idx].play(); }
      current = idx;
    }

    dots.forEach(dot => {
      dot.addEventListener("click", () => goToSlide(parseInt(dot.dataset.slide)));
    });

    // Swipe support for mobile
    let startX = 0;
    const media = card.querySelector(".product-media");
    media.addEventListener("touchstart", e => { startX = e.touches[0].clientX; }, { passive: true });
    media.addEventListener("touchend", e => {
      const diff = startX - e.changedTouches[0].clientX;
      if (Math.abs(diff) > 40) {
        if (diff > 0 && current < slides.length - 1) goToSlide(current + 1);
        else if (diff < 0 && current > 0) goToSlide(current - 1);
      }
    }, { passive: true });
  });
}

// ===== RENDER TESTIMONIALS =====
function renderTestimonials() {
  const grid = document.getElementById("testimonialsGrid");
  grid.innerHTML = testimonials.map((t, idx) => `
    <div class="testimonial-card reveal" style="transition-delay: ${idx * 0.1}s">
      <div class="testimonial-stars">★★★★★</div>
      <p class="testimonial-text">"${t.text}"</p>
      <div class="testimonial-author">
        <div class="testimonial-avatar">${t.initials}</div>
        <div>
          <div class="testimonial-name">${t.name}</div>
          <div class="testimonial-location">📍 ${t.location}</div>
        </div>
      </div>
    </div>
  `).join("");
}

// ===== NAVBAR SCROLL EFFECT =====
function initNavbar() {
  const navbar = document.getElementById("navbar");
  const toggle = document.getElementById("navToggle");
  const menu = document.getElementById("navMenu");

  window.addEventListener("scroll", () => {
    navbar.classList.toggle("scrolled", window.scrollY > 50);
  });

  toggle.addEventListener("click", () => {
    toggle.classList.toggle("open");
    menu.classList.toggle("open");
  });

  // Close menu on link click
  menu.querySelectorAll("a").forEach(link => {
    link.addEventListener("click", () => {
      toggle.classList.remove("open");
      menu.classList.remove("open");
    });
  });
}

// ===== SCROLL REVEAL (IntersectionObserver) =====
function initReveal() {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry, i) => {
      if (entry.isIntersecting) {
        setTimeout(() => {
          entry.target.classList.add("active");
        }, i * 80);
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1, rootMargin: "0px 0px -50px 0px" });

  document.querySelectorAll(".reveal, .reveal-left, .reveal-scale").forEach(el => {
    observer.observe(el);
  });
}

// ===== COUNTER ANIMATION =====
function initCounters() {
  const counters = document.querySelectorAll("[data-count]");
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const el = entry.target;
        const target = parseInt(el.dataset.count);
        const duration = 2000;
        const start = performance.now();
        
        function update(now) {
          const elapsed = now - start;
          const progress = Math.min(elapsed / duration, 1);
          const eased = 1 - Math.pow(1 - progress, 3);
          el.textContent = Math.floor(target * eased).toLocaleString() + (target < 100 ? "%" : "+");
          if (progress < 1) requestAnimationFrame(update);
        }
        requestAnimationFrame(update);
        observer.unobserve(el);
      }
    });
  }, { threshold: 0.5 });

  counters.forEach(c => observer.observe(c));
}

// ===== NANO BANANA PARALLAX EFFECT =====
function initNanoParallax() {
  let ticking = false;
  window.addEventListener("scroll", () => {
    if (!ticking) {
      requestAnimationFrame(() => {
        const scrollY = window.scrollY;
        // Subtle parallax on product cards
        document.querySelectorAll(".product-card").forEach((card, i) => {
          const rect = card.getBoundingClientRect();
          const centerY = rect.top + rect.height / 2;
          const viewportCenter = window.innerHeight / 2;
          const offset = (centerY - viewportCenter) * 0.02;
          card.style.transform = `translateY(${-offset}px)`;
        });
        // Parallax on hero content
        const heroContent = document.querySelector(".hero-content");
        if (heroContent && scrollY < window.innerHeight) {
          heroContent.style.transform = `translateY(${scrollY * 0.15}px)`;
          heroContent.style.opacity = 1 - scrollY / (window.innerHeight * 0.8);
        }
        ticking = false;
      });
      ticking = true;
    }
  });
}

// ===== MAGNETIC BUTTONS =====
function initMagneticButtons() {
  document.querySelectorAll(".magnetic-btn").forEach(btn => {
    btn.addEventListener("mousemove", (e) => {
      const rect = btn.getBoundingClientRect();
      const x = e.clientX - rect.left - rect.width / 2;
      const y = e.clientY - rect.top - rect.height / 2;
      btn.style.transform = `translate(${x * 0.15}px, ${y * 0.15}px)`;
    });
    btn.addEventListener("mouseleave", () => {
      btn.style.transform = "translate(0, 0)";
    });
  });
}

// ===== SMOOTH ANCHOR SCROLL =====
function initSmoothScroll() {
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener("click", (e) => {
      e.preventDefault();
      const target = document.querySelector(anchor.getAttribute("href"));
      if (target) {
        const offset = 80;
        const top = target.getBoundingClientRect().top + window.scrollY - offset;
        window.scrollTo({ top, behavior: "smooth" });
      }
    });
  });
}

// ===== CURSOR GLOW EFFECT =====
function initCursorGlow() {
  const glow = document.createElement("div");
  glow.style.cssText = `
    position: fixed; width: 300px; height: 300px; border-radius: 50%;
    background: radial-gradient(circle, rgba(0,212,170,0.04) 0%, transparent 70%);
    pointer-events: none; z-index: 0; transform: translate(-50%, -50%);
    transition: opacity 0.3s;
  `;
  document.body.appendChild(glow);
  
  document.addEventListener("mousemove", (e) => {
    glow.style.left = e.clientX + "px";
    glow.style.top = e.clientY + "px";
  });
}

// ===== RENDER PRODUCT DETAILS (product.html) =====
function renderProductDetails() {
  const container = document.getElementById("productDetailsContainer");
  if (!container) return;
  
  const params = new URLSearchParams(window.location.search);
  const id = parseInt(params.get("id"));
  const p = products.find(prod => prod.id === id);
  
  if (!p) {
    container.innerHTML = `<div style="text-align:center; grid-column:1/-1; padding:100px 0;"><h2>Produit introuvable.</h2><a href="index.html" class="btn-primary" style="margin-top:20px;">Retour à la boutique</a></div>`;
    return;
  }
  
  let mediaHTML = "";
  let thumbsHTML = "";
  
  if (p.images && p.images.length > 0) {
    p.images.forEach((src, i) => {
      mediaHTML += `<img src="${src}" class="main-media-item ${i===0?'active':''}" data-idx="${i}">`;
      thumbsHTML += `<div class="thumbnail ${i===0?'active':''}" data-target="${i}"><img src="${src}"></div>`;
    });
    if (p.video) {
      const idx = p.images.length;
      mediaHTML += `<video src="${p.video}" class="main-media-item" data-idx="${idx}" muted loop playsinline></video>`;
      thumbsHTML += `<div class="thumbnail" data-target="${idx}"><video src="${p.video}" muted></video></div>`;
    }
  } else {
    const img1 = p.img1 || generateProductImage(p, 0);
    const img2 = p.img2 || generateProductImage(p, 1);
    mediaHTML += `<img src="${img1}" class="main-media-item active" data-idx="0">`;
    mediaHTML += `<img src="${img2}" class="main-media-item" data-idx="1">`;
    thumbsHTML += `<div class="thumbnail active" data-target="0"><img src="${img1}"></div>`;
    thumbsHTML += `<div class="thumbnail" data-target="1"><img src="${img2}"></div>`;
  }

  const waMsg = encodeURIComponent(`Bonjour! Je souhaite commander: ${p.name} (${p.price} MAD).`);
  
  container.innerHTML = `
    <div class="product-gallery">
      <div class="main-media-container" id="mainMedia">
        ${mediaHTML}
      </div>
      <div class="thumbnails" id="thumbnails">
        ${thumbsHTML}
      </div>
    </div>
    <div class="product-details reveal">
      <span class="pd-badge">${p.badge}</span>
      <h1 class="pd-title">${p.name}</h1>
      <div class="pd-reviews">
        <span class="pd-stars">★★★★★</span>
        <span>(128 avis vérifiés)</span>
      </div>
      <div class="pd-price-row">
        <span class="pd-price">${p.price} MAD</span>
        <span class="pd-old-price">${p.oldPrice} MAD</span>
      </div>
      <p class="pd-desc">${p.desc}</p>
      
      <div class="pd-features">
        <div class="pd-feature"><div class="pd-feature-icon">🚀</div> Livraison Express partout au Maroc</div>
        <div class="pd-feature"><div class="pd-feature-icon">💰</div> Paiement à la réception</div>
        <div class="pd-feature"><div class="pd-feature-icon">✅</div> Garantie Satisfait ou Remboursé</div>
      </div>
      
      <a href="https://wa.me/${WHATSAPP_NUMBER}?text=${waMsg}" target="_blank" class="btn-whatsapp magnetic-btn pd-cta">
        ${whatsappSVG} Commander Maintenant
      </a>
      
      <div class="pd-urgency">
        <span class="dot"></span> En stock - Plus que quelques articles disponibles!
      </div>
    </div>
  `;
  
  // Gallery logic
  const thumbs = document.querySelectorAll(".thumbnail");
  const mainItems = document.querySelectorAll(".main-media-item");
  thumbs.forEach(t => {
    t.addEventListener("click", () => {
      thumbs.forEach(thumb => thumb.classList.remove("active"));
      mainItems.forEach(item => { item.classList.remove("active"); if (item.tagName === "VIDEO") item.pause(); });
      t.classList.add("active");
      const targetIdx = t.dataset.target;
      const targetItem = document.querySelector(`.main-media-item[data-idx="${targetIdx}"]`);
      if (targetItem) {
        targetItem.classList.add("active");
        if (targetItem.tagName === "VIDEO") targetItem.play();
      }
    });
  });
  initMagneticButtons();
  initReveal();
}

// ===== INIT =====
document.addEventListener("DOMContentLoaded", () => {
  const isProductPage = window.location.pathname.includes("product.html");
  
  initNavbar();
  initSmoothScroll();
  initCursorGlow();
  
  if (isProductPage) {
    renderProductDetails();
  } else {
    const grid = document.getElementById("productsGrid");
    if (grid) {
      renderProducts();
      renderTestimonials();
      initReveal();
      initCounters();
      initNanoParallax();
      initMagneticButtons();
    }
  }
});
